### ISSUE TITLE
What ?

### ISSUE THREAD

**Issue by Kaeldazs** [Kaeldazs/Appworks-2#1]
Je viens de voir que y'avais 3 personnes qui suivaient Appworks 2 =O

Si ça vous intéresse je peux mettre en ligne le logiciel packagé pour windows/mac.
Il est pas vraiment fini, mais il est bien avancé, et il fonctionne plutôt bien à l'heure actuelle.

**Comment by Kaeldazs** [comment]
Ah et si vous voulez participer, n'hésitez pas, je me tâte encore pour en faire un "projet d'excellence" !

**Comment by Kileahh** [comment]
J'ai trouvé comment y accéder ici, enfin !!
