### ISSUE TITLE
Traductions

### ISSUE THREAD

**Issue by Kaeldazs** [Kaeldazs/Appworks-2#4]
J'aurais besoin de quelqu'un sachant parler correctement Anglais pour jeter un œil aux traductions =P

**Comment by Kileahh** [comment]
Je regarde ça.

**Comment by Kaeldazs** [comment]
Oki, c'est dans js/language.js

**Comment by Kileahh** [comment]
Ok

**Comment by Kileahh** [comment]
Si il y a des modifications, je peux les pousser directement ? Où je t'envoie les fichiers par un autre mode de transmission ?

**Comment by Kaeldazs** [comment]
J'ai vu que tu avais fait un fork, tu n'as qu'as commit dedans, on pourra merge les deux ensuite

**Comment by Kileahh** [comment]
ok

**Comment by Kileahh** [comment]
Par contre, un détail sur GitHub que j'ai pas compris, c'est que mon forks est 12 commits derrière le tien, je je ne vois pas comment le rendre à jour, il y a pas de bouton de synchro

**Comment by Kaeldazs** [comment]
Bien sur, tu as décider de piquer mon code, tu veux pas en plus qu'il se synchronise tout seul ? Haha, je plaisante, tu doit bien avoir un moyen de récupérer la dernière version, surtout que le language.js à un peu changé. Quitte à le faire à la main =/

**Comment by Kileahh** [comment]
Héhé, Poutine est demandeur. Je vais faire à la main du coup un copier entre les repos sur mon pc, puis poussé sur le master

**Comment by Kaeldazs** [comment]
Je ne préfère pas que tu push sur le master de ce git directement

**Comment by Kileahh** [comment]
Ni moi, je fais des copies propre et je vérifie deux fois sur mon pc avec d'envoyer sur le fork

**Comment by Kaeldazs** [comment]
Parfait, merci =)

**Comment by Kileahh** [comment]
Dans langage.js, il y a des traductions en anglais qui n'existe pas en français. Normal, ou je les rajoute ?

**Comment by Kaeldazs** [comment]
J'ai dû oublier de les retirer, my bad. Si elle n'y sont pas en français c'est qu'elles ne sont pas utiles

**Comment by Kileahh** [comment]
Ok ok.

**Comment by Kileahh** [comment]
Voilà, j'ai push chez moi...

**Comment by Kaeldazs** [comment]
Génial merci ! Je regarde dès que j'ai le temps ! =)

**Comment by Kileahh** [comment]
Ok ok

**Comment by Kaeldazs** [comment]
Hop ! En faisant un mix des deux on a un truc pas mal ! Merci encore !
