### ISSUE TITLE
Oh !

### ISSUE THREAD

**Issue by Kaeldazs** [Kaeldazs/Appworks-2#5]
Mais où sont mes collaborateurs ? =O

**Comment by Kaeldazs** [comment]
Faudrait trouver un autre nom, Appworks c'est naze.

**Comment by Hundil** [comment]
Brain out
Pin me
Coworker
White board
( On ne me juge pas !)

**Comment by Kileahh** [comment]
(CowOrcKer)
MemBase
Little_Brother
Sticky

**Comment by Kaeldazs** [comment]
C'est pas mal Appworks

**Comment by MrSKRIIL** [comment]
octopoulpe

**Comment by Kileahh** [comment]
Yggdrasil,
NeutroSquid
Angstrom (taille d'un atome à priori)

**Comment by Kaeldazs** [comment]
![1477834831777](https://cloud.githubusercontent.com/assets/11888389/20104714/49b59176-a5cf-11e6-9f97-c64ce49dff1a.png)

**Comment by MrSKRIIL** [comment]
WAAAAZAAAAAA

**Comment by Kileahh** [comment]
AtomSquid

**Comment by Kileahh** [comment]
Kraktom

**Comment by Hundil** [comment]
y
