### ISSUE TITLE
Participation

### ISSUE THREAD

**Issue by Kaeldazs** [Kaeldazs/Appworks-2#6]
Si vous voulez participer, laissez un message ici.

Je vous expliquerais en live ce qu'il faut savoir, au niveau de node.js, electron, le packaging, comment fonctionne le logiciel en général, etc.

**Comment by Hundil** [comment]
Wesheux !

**Comment by Kileahh** [comment]
Yggdrasil,
NeutroSquid
Angstrom (taille d'un atome à priori)

**Comment by Kaeldazs** [comment]
![1477834831777](https://cloud.githubusercontent.com/assets/11888389/20104677/28dfaaea-a5cf-11e6-9617-75cacab6e040.png)

**Comment by MrSKRIIL** [comment]
![](https://s-media-cache-ak0.pinimg.com/236x/0e/3d/f6/0e3df60cabeec611be2872b82db57458.jpg)

**Comment by MrSKRIIL** [comment]
![unicorn](https://cloud.githubusercontent.com/assets/16242771/20106204/a2166fa2-a5d4-11e6-9a2b-b1c60d29ae25.jpg)
